### ISSUE TITLE
NEXT RELEASE: Webpacked Extension

### ISSUE THREAD

**Issue by mtxr** [mtxr/vscode-sqltools#115]
This is a guideline for the next release that will bring us some improvements.

This changes are happening on `master-webpack` branch, checkout and get it running to see how is it going.

Here is the checklist:

- [x] Setup Webpack
- [x] Change repository structure to a mono repo.
- [x] Migrate to the new Webview API #109 
- [x] Fixes language server issues like startup #107 #70 
- [x] Optional expanded cols #105
- [x] Remove the HTTP server and migrate to LSP
- [x] Allow multiple connections #69

This changes will give us a faster startup time, security with the new Webview API also structure to grow the extension and allow other to contribute to different parts of the extension.

I know that the release time has increased, but it will worth. I've been busy so I want to prepare the extension to keep growing by the community. This changes will decouple the code a lot, so it will be easier to contribute.

Comments and suggestions are welcome!

M.

**Comment by mickeypearce** [comment]
I am waiting for the Oracle version. Will it be included in this release as well?
